version: "3.9"
services:
  php-service:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: php-container
    restart: unless-stopped
    working_dir: /var/www/html/app
    volumes:
      - .:/var/www/html
    networks:
      - blog

  nginx-service:
    image: nginx:alpine
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - blog
  db-service:
    image: mysql:8
    container_name: db-container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - blog

networks:
  blog:
    driver: bridge
